apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  securityContext:
    sysctls:
    - name: kernel.msgmax
      value: "65535"
  containers:
  - name: box
    image: busybox
    # securityContext:
    #   procMount: Unmasked
    command: 
    - sh
    args:
    - -c
    - sleep 3600