apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anti-affinity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anti-affinity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pod-affinity
            topologyKey: kubernetes.io/hostname
      containers:
      - name: with-pod-affinity
        image: nginx
