apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    app: node-selector
spec:
  nodeSelector:
    workload_type: spot
  containers:
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
